namespace: "adampippert"
name: "acs_gitops"
version: "1.1.0"
readme: "README.md"
authors:
    - "Adam Pippert"
    - "Dinesh Lakshmanan"
    - "Neil Carpenter"
dependencies:
    "lvrfrc87.git_acp": ">=2.0.0"
license:
    - "MIT"
tags:
    - demo
    - collection
repository: "https://www.github.com/adampippert/acs-gitops"
